# Generated by Django 6.0.4 on 2026-08-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_vacunacion_id_vacuna_vacunacion_nombre_vacuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
