# Generated by Django 6.0.4 on 2026-08-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='mascota_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
