# Generated by Django 6.0.4 on 2026-08-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mascota_mascota_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='mascota_id',
        ),
    ]
